Introduce myself
white9p/first-repo pull request #1
Opened 2021-07-21 12:53 UTC by white9p

2021-07-21 13:25 UTC, kwonsean requested changes
첫번째 request

2021-07-21 13:25 UTC, kwonsean commented on introduction.html
> +<h1>자기소개</h1>
h1 을 h2로 변경해 보세요.

2021-07-21 13:25 UTC, kwonsean commented on introduction.html
> +저는 마린 블루 색을 좋아하고 겨울을 좋아해요. 그리고 밀크티를 좋아하고 수박을 싫어합니다. </br>여러분과 좋은 분위기를 만들어나가며 즐겁게 공부하고 싶습니다.</p><p>저에게 더 궁금한 것이 있으시다면 kmjkmj9905@naver.com으로 질문 보내주시기 바랍니다.</p>
br 을 기준으로 줄을 나누어 보세요. (12줄이 기니깐 엔터를 쳐서 나누어 보세요)

2021-07-23 04:46 UTC, white9p commented on introduction.html
> +저는 마린 블루 색을 좋아하고 겨울을 좋아해요. 그리고 밀크티를 좋아하고 수박을 싫어합니다. </br>여러분과 좋은 분위기를 만들어나가며 즐겁게 공부하고 싶습니다.</p><p>저에게 더 궁금한 것이 있으시다면 kmjkmj9905@naver.com으로 질문 보내주시기 바랍니다.</p>
got it!

2021-07-23 04:46 UTC, white9p commented on introduction.html
> +<h1>자기소개</h1>
Yes sir!

2021-07-23 08:22 UTC, kwonsean approved these changes

2021-07-23 08:23 UTC, kwonsean approved these changes
great job!

2021-07-27 13:30 UTC, merged